"use client";

/**
 * CAROUSEL preview — horizontal multi-slide with prev/next navigation.
 *
 * Uses the dedicated carousel_slides field from the draft. Each slide was
 * generated by Claude following the emotional escalation arc:
 *   threat → pain → escalation → realization → action
 *
 * Backward compatibility: if carousel_slides is missing (older drafts),
 * falls back to splitting the caption by double-newline paragraphs.
 */

import { useState, useMemo } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type { DraftFull, CarouselSlide } from "@/hooks/use-drafts";
import {
  PreviewFrame,
  GradientOverlay,
  HookText,
  CaptionText,
  CtaBadge,
  FormatBadge,
  SlideIndicator,
  WarGlow,
  GoldAccentLine,
  colors,
} from "./preview-primitives";

interface CarouselPreviewProps {
  draft: DraftFull;
}

/** Emotional arc labels mapped to slide position. */
const ARC_LABELS = ["איום", "כאב", "הסלמה", "הבנה", "פעולה"] as const;

function getArcLabel(index: number, total: number): string {
  if (total <= ARC_LABELS.length) {
    return ARC_LABELS[index] ?? `סלייד ${index + 1}`;
  }
  // For carousels with more than 5 slides, label first, last, and number the rest
  if (index === 0) return "איום";
  if (index === total - 1) return "פעולה";
  return `סלייד ${index + 1}`;
}

interface SlideData {
  text: string;
  isArc: boolean; // true = from carousel_slides (structured), false = fallback
}

function buildSlides(draft: DraftFull): SlideData[] {
  // Primary path: use carousel_slides directly
  const raw = draft.carouselSlides as CarouselSlide[] | null;
  if (raw && raw.length > 0) {
    return raw.map((s) => ({ text: s.text, isArc: true }));
  }

  // Fallback for older drafts without carousel_slides:
  // synthesize from hook + caption paragraphs + CTA
  const slides: SlideData[] = [];

  if (draft.hook) {
    slides.push({ text: draft.hook, isArc: false });
  }

  const caption = draft.facebookCaption || draft.instagramCaption || "";
  const paragraphs = caption
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);
  for (const p of paragraphs) {
    slides.push({ text: p, isArc: false });
  }

  if (draft.cta) {
    slides.push({ text: draft.cta, isArc: false });
  }

  if (slides.length === 0) {
    slides.push({ text: "אין תוכן לתצוגה", isArc: false });
  }

  return slides;
}

export function CarouselPreview({ draft }: CarouselPreviewProps) {
  const slides = useMemo(() => buildSlides(draft), [draft]);
  const [current, setCurrent] = useState(0);

  const prev = () => setCurrent((c) => Math.max(0, c - 1));
  const next = () => setCurrent((c) => Math.min(slides.length - 1, c + 1));

  const slide = slides[current];
  const isLastSlide = current === slides.length - 1;

  return (
    <div className="space-y-3" style={{ maxWidth: 420, width: "100%" }}>
      <PreviewFrame aspect="1/1" maxWidth={420}>
        <FormatBadge label={`CAROUSEL ${current + 1}/${slides.length}`} />
        <WarGlow />
        <GradientOverlay position="full" />

        {/* Slide content */}
        <div className="absolute inset-0 flex flex-col justify-center p-7 gap-4 z-[1]">
          {/* Arc label */}
          <span
            className="text-[10px] font-bold uppercase tracking-widest"
            style={{ color: colors.gold, opacity: 0.7 }}
          >
            {slide.isArc
              ? getArcLabel(current, slides.length)
              : current === 0
                ? "איום"
                : isLastSlide
                  ? "פעולה"
                  : `סלייד ${current + 1}`}
          </span>

          <GoldAccentLine />

          {/* Slide text — first slide gets hero treatment, last gets CTA badge */}
          {isLastSlide && slide.isArc ? (
            <>
              <HookText size="sm">{slide.text}</HookText>
              {draft.cta && (
                <div className="pt-2">
                  <CtaBadge>{draft.cta}</CtaBadge>
                </div>
              )}
            </>
          ) : current === 0 ? (
            <HookText size="md">{slide.text}</HookText>
          ) : (
            <CaptionText maxLines={6}>{slide.text}</CaptionText>
          )}
        </div>

        {/* Prev/Next buttons */}
        {slides.length > 1 && (
          <>
            {current > 0 && (
              <button
                onClick={prev}
                className="absolute right-2 top-1/2 -translate-y-1/2 z-10 w-8 h-8 rounded-full flex items-center justify-center transition-colors"
                style={{
                  backgroundColor: "rgba(45,49,72,0.7)",
                  color: colors.text,
                  backdropFilter: "blur(4px)",
                }}
                aria-label="Previous slide"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            )}
            {current < slides.length - 1 && (
              <button
                onClick={next}
                className="absolute left-2 top-1/2 -translate-y-1/2 z-10 w-8 h-8 rounded-full flex items-center justify-center transition-colors"
                style={{
                  backgroundColor: "rgba(45,49,72,0.7)",
                  color: colors.text,
                  backdropFilter: "blur(4px)",
                }}
                aria-label="Next slide"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
            )}
          </>
        )}
      </PreviewFrame>

      {/* Dot indicators */}
      {slides.length > 1 && (
        <SlideIndicator total={slides.length} current={current} />
      )}
    </div>
  );
}
